version: "3"

services:
  apt-test-server:
    container_name: 'apt-test-server'
    build: ./docker/bin/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    command: [nginx-debug, '-g', 'daemon off;']

  apt-test-app:
    build: ./docker/bin/php
    container_name: 'apt-test-app'
    volumes:
      - ./:/var/www
    user: "$UID"
