version: "3"

services:
  apt-test-server:
    container_name: 'apt-test-server'
    build: ./docker/bin/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    command: [nginx-debug, '-g', 'daemon off;']

  apt-test-app:
    build: ./docker/bin/php
    container_name: 'apt-test-app'
    volumes:
      - ./:/var/www
    user: "$UID"

  apt-test-mysql:
    image: mysql:5.7
    container_name: 'apt-test-mysql'
    ports:
      - "3307:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
